### ISSUE TITLE
puppeteer and node-qpdf2

### ISSUE THREAD

**Issue by masterbater** [Sparticuz/node-qpdf2#35]
Ive got this pdf buffer, does this lib supports buffer, and also output it as buffer in the latest version?
```typescript
  const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        timeout: 100000,
      });

```

**Comment by Sparticuz** [comment]
Qpdf doesn't support input from stdin, so no. But it does let you output as a buffer. Check out https://github.com/Sparticuz/node-qpdf2/blob/master/test/encrypt-and-decrypt.ts for examples

https://github.com/qpdf/qpdf/issues/54

You need to write it to /tmp then put that path into node-qpdf

**Comment by masterbater** [comment]
I got it working thanks I added path to puppeteer, only problem was the esm, I need to downgrade to v4 since Im using it in nestjs
