### ISSUE TITLE
Encryption and Decryption Password Protection is not working

### ISSUE THREAD

**Issue by karthiktanj** [Sparticuz/node-qpdf2#4]
When we are trying to make password protection below error is occuring. Could you please provide the solution to encrypt and decrypt the pdf with password protection

Error :spawn qpdf ENOENT

TypeScript Code :
var qpdf = require('node-qpdf2');
var file = path.join(__dirname, 'sample.pdf');

            const options = {
                keyLength: 128,
                password: 'test1234'
            }
            qpdf.encrypt(file, options);

**Comment by Sparticuz** [comment]
ENOENT is a 'No Entity Exists' error. Can you verify that qpdf is installed? https://github.com/qpdf/qpdf

**Comment by Sparticuz** [comment]
If that doesn't work, feel free to reopen.

**Comment by karthiktanj** [comment]
Could you please provide the steps how to install the qpdf in the Window 10

**Comment by Sparticuz** [comment]
Here is the link to the qpdf releases, take a look at the mingw or msvc zips, both should work on windows. https://github.com/qpdf/qpdf/releases. Side note: I haven't tested this package on windows, just unix systems. If there are problems after you get qpdf up and running, file an issue.
