### ISSUE TITLE
spawn qpdf ENOENT

### ISSUE THREAD

**Issue by AndreGiuseppin** [Sparticuz/node-qpdf2#42]
Hello, I'm trying to use the version 4.1.0 because the CommonJs.

But when I try to encrypt a file, I receive the following error: 

`Erro: Error: spawn qpdf ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn qpdf',
  path: 'qpdf',
  spawnargs: [
    '--encrypt',
    '1234',
    '1234',
    '256',
    '--',
    './pdfs/teste.pdf',
    '-'
  ]`

Edit: Now I see that I need to install qpdf dependencie in my machine, but I have one more question, can I run this lib in Aws Lambda?

**Comment by Sparticuz** [comment]
Yes, qpdf actually provides a package that works as a layer.

**Comment by guillemest** [comment]
Hello I know this is closed but, I was looking into this and I can't figure it out. I'm getting the same error is there any specific package? Trying to run qpdf latest version 6.1.0 and node v18.17.0. Thanks!

**Comment by Sparticuz** [comment]
That error means that the node package can't find qpdf installed. Make sure you have the layer applied correctly on Lambda.

**Comment by guillemest** [comment]
In this case I'm running the project locally on a Windows PC

**Comment by Sparticuz** [comment]
Ah, the comment still stands though, that message means node-qpdf can't find the qpdf application installed in your system's PATH.

**Comment by guillemest** [comment]
Awesome thanks for your reply I'll take look again
