### ISSUE TITLE
Make password optional in decrypt

### ISSUE THREAD

**Issue by arthurRbr** [Sparticuz/node-qpdf2#7]
Hi,

Could you make the password an optional input in `decrypt.js` ? 
Qpdf actually allows to decrypt a pdf without providing a password, or with a blank string as a password
 
`qpdf --decrypt input.pdf output.pdf`

Thanks

**Comment by Sparticuz** [comment]
Hey there, I have no idea why github didn't notify me of issues in this repo. I've started looking at this issue. Sorry for the delay.

**Comment by Sparticuz** [comment]
It looks like you need to enter `""` as the value for password. See: https://stackoverflow.com/questions/42785645/qpdf-fails-to-encrypt-without-passwords

Regardless, I've added a test for blank passwords to catch this in the future. (And for documentation)

Thanks for the issue and sorry I didn't see this sooner!
