### ISSUE TITLE
No such file or directory - file name contains a space

### ISSUE THREAD

**Issue by evolutionxbox** [Sparticuz/node-qpdf2#8]
> I have also added an issue on [node-qpdf](https://github.com/nrhirani/node-qpdf/issues/16)

Trying to encrypt a file that has one or more spaces in the name

```js
qpdf
    .encrypt(
      '/Users/my/absolute/path/to/A Sample PDF.pdf',
      {
        keyLength: 40,
        password: {
          user: '',
          owner: 'YOUR_PASSWORD_TO_ENCRYPT_FOR_OWNER',
        },
        restrictions: {
          print: 'y',
        },
      },
      '/Users/my/absolute/path/to/protected.pdf'
    )
    .then((x) => console.log('Done: ', x))
    .catch((e) => console.error('Error: ', e));
```

Result:
```sh
Error:  open /Users/my/absolute/path/to/A\ Sample\ PDF.pdf: No such file or directory
```

I thought that maybe adding double quotes around the path would help, as that is what you do in the shell to allow paths with spaces:

```js
qpdf
    .encrypt(
      '"/Users/my/absolute/path/to/A Sample PDF.pdf"',
      {
        keyLength: 40,
        password: {
          user: '',
          owner: 'YOUR_PASSWORD_TO_ENCRYPT_FOR_OWNER',
        },
        restrictions: {
          print: 'y',
        },
      },
      '/Users/my/absolute/path/to/protected.pdf'
    )
    .then((x) => console.log('Done: ', x))
    .catch((e) => console.error('Error: ', e));
```

Result:
```sh
Done:  Input file doesn't exist
```

Using `path.resolve` also results in the "Input file doesn't exist" error.

**Comment by Sparticuz** [comment]
Hey there, I have no idea why github didn't notify me of issues in this repo. I've started looking at this bug. Sorry for the delay.

**Comment by Sparticuz** [comment]
I'm not sure why, but I was manually escaping the input variable. I changed that and added tests for this case. Thanks for the issue and sorry I missed it for so long!
